language: java
jdk:
  - openjdk11
services:
  - docker
cache:
  directories:
  - $HOME/.m2

install: true
script: mvn package

before_deploy:
  - docker-compose -f etc/docker/docker-compose-dev.yml build
