name: Push to Docker Hub
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Build the Docker image
      run: docker build . --file etc/docker/Dockerfile-dev --tag ${{ secrets.DOCKERHUB_REGISTRY }}/legal-consultation-api

    - name: Login to docker hub registry
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Push to docker hub registry
      run: docker push ${{ secrets.DOCKERHUB_REGISTRY }}/legal-consultation-api:latest
